services:
  exchange-rate-service:
    build: 
      context: .
      args:
        BUILD_MODE: release
        VERSION: ${VERSION:-1.0.0}
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - GIN_MODE=release
