services:
  exchange-rate-service:
    build: 
      context: .
      args:
        BUILD_MODE: ${BUILD_MODE:-debug}
        VERSION: ${VERSION:-dev}
    ports:
      - "8080:8080"
    env_file:
      - .env