global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'exchange-rate-service'
    static_configs:
      - targets: ['exchange-rate-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
